os: linux

dist: xenial

sudo: false

addons:
  apt:
    packages:
      - xvfb
  chrome: beta

language: node_js

node_js:
  - '8'
  - '10'
  - '11'
  - 'lts/*'

git:
  depth: 3

cache: npm

services:
  - xvfb

script:
  - npm run lint
# - xvfb-run -a npm test
